name: streamlit-insulin-needs
channels:
  - conda-forge
  - maxibor
  - defaults
dependencies:
  - python=3.11
  - streamlit>=1.29.0
  - numpy
  - matplotlib
  - seaborn
  - pandas>=2.0.0
  - scipy
  - pytest
  - pyhamcrest
  - plotly>=5.18.0
  - pip
#  - pip:
